package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"io"
	"log"
	"maps"
	"net/http"
	"os"
	"regexp"
	"slices"
	"strings"
)

const sourceURL = "https://files.helium.computer/bangs.json"

type SourceBang struct {
	Triggers []string `json:"ts"`
	URL      string   `json:"u"`
}

type Bang struct {
	Prefix string
	Suffix string
}

func main() {
	resp, err := http.Get(sourceURL)
	if err != nil {
		log.Fatal(err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		log.Fatalf("download failed: %s", resp.Status)
	}

	body, err := io.ReadAll(resp.Body)
	if err != nil {
		log.Fatal(err)
	}

	body = cleanJSONC(body)

	var src []SourceBang
	if err := json.Unmarshal(body, &src); err != nil {
		log.Fatal(err)
	}

	bangs := make(map[string]Bang)

	for _, bang := range src {
		prefix, suffix, found := strings.Cut(bang.URL, "{searchTerms}")
		if !found {
			prefix = bang.URL
			suffix = ""
		}

		b := Bang{
			Prefix: prefix,
			Suffix: suffix,
		}

		for _, trigger := range bang.Triggers {
			bangs[strings.ToLower(trigger)] = b
		}
	}

	var out bytes.Buffer

	fmt.Fprintln(&out, "// Code generated by go generate; DO NOT EDIT.")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "package main")
	fmt.Fprintln(&out)
	fmt.Fprintln(&out, "var Bangs = map[string]Bang{")

	keys := slices.Sorted(maps.Keys(bangs))

	for _, key := range keys {
		b := bangs[key]
		fmt.Fprintf(&out, "%q:{Prefix:%q,Suffix:%q},\n", key, b.Prefix, b.Suffix)
	}

	fmt.Fprintln(&out, "}")

	formatted, err := format.Source(out.Bytes())
	if err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile("bangs.go", formatted, 0644); err != nil {
		log.Fatal(err)
	}

	fmt.Printf("Generated %d bangs\n", len(bangs))
}

func cleanJSONC(input []byte) []byte {
	text := string(input)

	// Remove full-line comments
	lines := strings.Split(text, "\n")
	filtered := make([]string, 0, len(lines))
	for _, line := range lines {
		if !strings.HasPrefix(strings.TrimSpace(line), "//") {
			filtered = append(filtered, line)
		}
	}

	text = strings.Join(filtered, "\n")

	// Remove trailing commas before } or ]
	reTrailingComma := regexp.MustCompile(`,\s*([}\]])`)
	text = reTrailingComma.ReplaceAllString(text, "$1")

	return []byte(strings.TrimSpace(text))
}
